### ISSUE TITLE
Train Algorithm

### ISSUE THREAD

**Issue by tamuseanmiller** [tamuseanmiller/alpaca-stock-trading-bot#1]
The algorithm for the number of years isn't correct and runs for long periods of time.

**Comment by tamuseanmiller** [comment]
Updated with last commit

**Comment by GitHubEmploy** [comment]
Hey, I am using the train algo, and for me, it's taking a very long time for some reason. I was running it constantly for the last 72 hours and it's only done one episode. I am running this on a Tesla K80 for computing, so it should work really fast. IDK what happened.

**Comment by tamuseanmiller** [comment]
> Hey, I am using the train algo, and for me, it's taking a very long time for some reason. I was running it constantly for the last 72 hours and it's only done one episode. I am running this on a Tesla K80 for computing, so it should work really fast. IDK what happened.

There are a few reasons for this. Where the largest is because I messed up the training algorithm and am working on the update for it in integration right now.

**Comment by GitHubEmploy** [comment]
Okay, cool thank you for letting me know. Please tell me when the update is finished.

**Comment by tamuseanmiller** [comment]
> Okay, cool thank you for letting me know. Please tell me when the update is finished.

Just working on some final testing for it, the train algorithm is complete if you want to download it from integration. You can even test it for me, if you would like.

**Comment by GitHubEmploy** [comment]
Ok, cool, I am going to test it out right now, and give you the results

**Comment by GitHubEmploy** [comment]
args = docopt(__doc__) #Line 195, train.py, Version Integration
This line gives an error saying that it requires a byte like an object, so I replaced the arguments with variables.

**Comment by tamuseanmiller** [comment]
> args = docopt(__doc__) #Line 195, train.py, Version Integration
> 
> This line gives an error saying that it requires a byte like an object, so I replaced the arguments with variables.

Sorry to do this, but I hadn't pushed the latest version. Should have added functionality and fix that error. Let me know if it happens again.

**Comment by GitHubEmploy** [comment]
Ok, so testing it the results are way better. Instead of 72 hours, it took me 10 minutes to train 1 episode! This works way better and I think that this is good so far. Also, the docopt error is also happening in the new version of your eval file so you need to fix that there too. Thank You.

**Comment by GitHubEmploy** [comment]
Also wondering, why do you force it to use CPU? Wouldnt GPU be faster?

**Comment by tamuseanmiller** [comment]
> Also wondering, why do you force it to use CPU? Wouldnt GPU be faster?

Training in this way is actually faster using CPU according to the original author

**Comment by tamuseanmiller** [comment]
> Ok, so testing it the results are way better. Instead of 72 hours, it took me 10 minutes to train 1 episode! This works way better and I think that this is good so far. Also, the docopt error is also happening in the new version of your eval file so you need to fix that there too. Thank You.

I was wondering, can you reproduce this docopt error? I can't seem to trigger it.
