### ISSUE TITLE
NOT ISSUE: Question

### ISSUE THREAD

**Issue by GitHubEmploy** [tamuseanmiller/alpaca-stock-trading-bot#12]
Hey, I was wondering if I could have your trading data for the files. The data inside data/STOCK.csv. I need this because it learns as it trades, right? So if I have a month of trading data, it will become better at trading this stock.

**Comment by tamuseanmiller** [comment]
The new train.py will automatically call Polygon's api for data if you have a funded account. I can add them, just making sure you knew

**Comment by GitHubEmploy** [comment]
That's not what I meant but helpful, what I meant is that can I have the trading data from YOUR computer because then I can have a very trained model.

**Comment by tamuseanmiller** [comment]
> That's not what I meant but helpful, what I meant is that can I have the trading data from YOUR computer because then I can have a very trained model.

I think I'm confused, you want training and test csv's?

**Comment by GitHubEmploy** [comment]
No, the TRADING data
 from your computer.
![Screen Shot 2020-10-24 at 6 15 58 PM](https://user-images.githubusercontent.com/65371337/97096718-f893c680-1624-11eb-9919-cb8b2fe209a5.png)

**Comment by tamuseanmiller** [comment]
Ah, it will be more helpful for you to just train on historical data, there's no real benefit. I've also switched entirely to mongodb

**Comment by GitHubEmploy** [comment]
oh, ok than you
