### ISSUE TITLE
NOT ISSUE: Improvement

### ISSUE THREAD

**Issue by GitHubEmploy** [tamuseanmiller/alpaca-stock-trading-bot#13]
Hey, just an idea, when the stock market closes, instead of saying, "These many minutes still stock market opens", you could set it to train the model when the stock market closed, and trade when stock market open. Therefore, it becomes smarter every day. Because what I see is the bot wasting 14 hours of processing power when it could be training the model and becoming smarter. Again, just an idea. I can also do this for you if you want because I already implemented this on a different bot.

**Comment by tamuseanmiller** [comment]
This has it's ups and downs, the biggest down is that if you train it too much on historical data then it will get to a point where it will buy one stock and sell one stock at the beginning of each day.

That's definitely the reason I wouldn't personally implement it, I find that training a model that I'm happy with and then letting it learn with news data is optimal for me. Also, the bot isn't really using any resources during that interim period so it's not really a deal breaker. If you wish to implement it into your own bot though, feel free!
